In [1]:
integer_scalar = 42
print(integer_scalar)

42


In [2]:
a = 5
b = 2
sum_result = a + b
product_result = a * b
is_greater = a > b
is_equal = a == b
print(sum_result)
print(product_result)
print(is_greater)
print(is_equal)

7
10
True
False


In [3]:
import numpy as np

vector1 = np.array([1, 2, 3])  
vector2 = np.array([4, 5, 6])

result_addition = vector1 + vector2
print("Vector Addition:", result_addition)

result_subtraction = vector1 - vector2
print("Vector Subtraction:", result_subtraction)

scalar = 2
result_scalar_multiplication = scalar * vector1
print("Scalar Multiplication:", result_scalar_multiplication)

dot_product = np.dot(vector1, vector2)
print("Dot Product:", dot_product)

vector3 = np.array([7, 8, 9])
cross_product = np.cross(vector1, vector3)
print("Cross Product:", cross_product)

magnitude_vector1 = np.linalg.norm(vector1)
print("Magnitude of Vector1:", magnitude_vector1)

unit_vector1 = vector1 / np.linalg.norm(vector1)
print("Unit Vector of Vector1:", unit_vector1)

Vector Addition: [5 7 9]
Vector Subtraction: [-3 -3 -3]
Scalar Multiplication: [2 4 6]
Dot Product: 32
Cross Product: [-6 12 -6]
Magnitude of Vector1: 3.7416573867739413
Unit Vector of Vector1: [0.26726124 0.53452248 0.80178373]


In [4]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

result_addition = matrix_a + matrix_b

result_subtraction = matrix_a - matrix_b

result_element_wise = matrix_a * matrix_b

result_matrix_multiply = np.dot(matrix_a, matrix_b)

matrix_a_transpose = np.transpose(matrix_a)

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nAddition of matrices A and B:")
print(result_addition)

print("\nSubtraction of matrices A and B:")
print(result_subtraction)

print("\nElement-wise multiplication of matrices A and B:")
print(result_element_wise)

print("\nMatrix multiplication (dot product) of matrices A and B:")
print(result_matrix_multiply)

print("\nTranspose of matrix A:")
print(matrix_a_transpose)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of matrices A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of matrices A and B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise multiplication of matrices A and B:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix multiplication (dot product) of matrices A and B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
import numpy as np

def f(x):
    return x**2 + 3*x + 2


x = np.array(2.0) 
learning_rate = 0.1 
n_iterations = 100 

for _ in range(n_iterations):
    gradient = 2 * x + 3 
    x = x - learning_rate * gradient 

print("Minimum of the function:", f(x))

Minimum of the function: -0.24999999999999956


In [6]:
import numpy as np

A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [7]:
import numpy as np

A = np.array([[3, 1],
              [1, 2]])

frobenius_norm = np.linalg.norm(A, 'fro')
print("Frobenius Norm:", frobenius_norm)

two_norm = np.linalg.norm(A, 2)
print("2-Norm:", two_norm)

inf_norm = np.linalg.norm(A, np.inf)
print("Infinity Norm:", inf_norm)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Frobenius Norm: 3.872983346207417
2-Norm: 3.6180339887498953
Infinity Norm: 4.0
Eigenvalues: [3.61803399 1.38196601]
Eigenvectors:
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
